<?php

namespace AppBundle\Repository;

/**
 * CircuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCircuitsWithProgrammation(){
		$query = $this->getEntityManager()
		->createQuery(
				'SELECT c FROM AppBundle:Circuit c, AppBundle:ProgrammationCircuit p
	            WHERE p.circuit = c.id'
				);
				return $query->getArrayResult();
	
	
	}
	
}
